### ISSUE TITLE
Installer for packaging program

### ISSUE THREAD

**Issue by dougdoner** [Flock-of-Seagles-CSCD350/Trivia-Maze#15]
I haven't looked too much into this, but could we use Maven to help wrap the program in an executable? I do see there are Maven packages for Launch4j (the example program Tom introduced in class).

**Comment by JustQubit** [comment]
[This page](https://github.com/lukaszlenart/launch4j-maven-plugin/blob/master/src/main/resources/README.adoc) might be useful for us later. Looks like we can wrap the whole thing in an executable, and even add separate ones for running in console mode (for the console version of the AdminUI) or in GUI mode (the actual game).

**Comment by dougdoner** [comment]
Oh okay thanks @GamerBah, that will probably fix #14 too, we don't necessarily need a GUI for admin stuff if we can package the console up.

**Comment by dougdoner** [comment]
iteration-4-installer branch addresses this.
