### ISSUE TITLE
Java CI Workflow picks up SQL errors during maven tests

### ISSUE THREAD

**Issue by JustQubit** [Flock-of-Seagles-CSCD350/Trivia-Maze#18]
I noticed in the Java CI Workflow Maven action, the tests are throwing `org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)` errors. Not sure if this is anything to be worried about? Everything still passes, but I can't imagine errors like this are good.

**Comment by dougdoner** [comment]
9e178ab fixes this issue. I was originally deleting all of the tables before each test because I was running into issues with malformed data, but the foreign-key support I added should fix all that.
